apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: gsqa-kube-collector-letsencrypt

spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: {{ .Values.cert.email }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: gsqa-kube-collector-letsencrypt
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: {{ .Values.ingress.class }}
