apiVersion: v2
name: gsqa-kube-collector
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
- name: kube-state-metrics
  version: "2.x.x"
  repository: "https://charts.bitnami.com/bitnami"

- name: ingress-nginx
  version: "3.x.x"
  repository: "https://kubernetes.github.io/ingress-nginx"
  condition: ingress-nginx.enabled